You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/home/lgpu0034/.local/lib/python3.6/site-packages/matplotlib/font_manager.py:281: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  'Matplotlib is building the font cache using fc-list. '
Traceback (most recent call last):
  File "/home/lgpu0034/uva_deeplearning/assignment_1/code/train_convnet_pytorch.py", line 199, in <module>
    main()
  File "/home/lgpu0034/uva_deeplearning/assignment_1/code/train_convnet_pytorch.py", line 182, in main
    train()
  File "/home/lgpu0034/uva_deeplearning/assignment_1/code/train_convnet_pytorch.py", line 139, in train
    save_plots('cnn.png', losses, val_acc)
  File "/home/lgpu0034/uva_deeplearning/assignment_1/code/train_convnet_pytorch.py", line 153, in save_plots
    fig, ax1 = plt.subplots()
  File "/home/lgpu0034/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 1184, in subplots
    fig = figure(**fig_kw)
  File "/home/lgpu0034/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/home/lgpu0034/.local/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/lgpu0034/.local/lib/python3.6/site-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/hpc/eb/Debian9/Python/3.6.3-foss-2017b/lib/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
